### ISSUE TITLE
Define pages and their content

### ISSUE THREAD

**Issue by NickKolpin** [OxfordHackspace/publicWeb#4]
The current site is all in one page. It needs to expand into a small number of pages. Below is a proposed organisation of the content:

* **Main page**:
    * Directions to hackspace
    * Calendar/list of upcoming events
    * Contant information, link to mailing list, etc.
* **About page**:
    * What a hackspace is
    * Our history
* **Membership page**:
    * Benefits of becoming a member
    * Cost of becoming a member
    * Instructions how to become a member
    * Link to members only pages when they come online
* **Services page**: 
    * List of services we provide
    * List of services we plan to provide
    * List of useful services provided by others
    * **3D printing service page**:
        * What the service offers
        * Cost structure
        * Instructions how to start an order

What do people think of this proposal? Please comment with any suggested changes, etc.

**Comment by MetaFight** [comment]
looks good to me.

**Comment by NickKolpin** [comment]
I pushed 2995069d80, which has bare bones pages organised as detailed above.

**Comment by NickKolpin** [comment]
I've now implemented this structure, but need the pages need actual content.
